"""Emit the per-page string tables that the templates include, from `l10n/*.json`.

The catalog is the source of truth; these generated files are the only thing
that knows the pages are rendered in the browser today. If Synapse ever grows
template localization (matrix-org/synapse#9386) or these pages move elsewhere,
this emitter is the piece that gets replaced -- the catalog and every
translation carry over unchanged. See
.github/instructions/localization.instructions.md.

Catalog keys are namespaced by page (`accountDetails.heading`); the prefix
selects which generated file a key lands in, so a page only ships its own copy.

Jinja safety: the generated tables are pulled into templates with
`{% include %}`, and catalog values contain `{{ server_name }}`-style
placeholders. Emitting them as a bare object literal would hand Jinja its own
delimiters and it would render the placeholders away. So the table is emitted
as a JSON string with every `{` escaped to `\\u007b` and parsed at runtime --
no Jinja delimiter survives into the file.

Usage:
  uv run scripts/translate/emit_l10n.py            # regenerate templates/l10n_*.js
  uv run scripts/translate/emit_l10n.py --check    # CI: fail if they are stale
"""

# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///

import argparse
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent.parent

# Key prefix -> generated template. A page not listed here is not localized.
PAGES = {
    "accountDetails": "l10n_sso_auth_account_details.js",
    "redirectConfirm": "l10n_sso_redirect_confirm.js",
    "ssoError": "l10n_sso_error.js",
    "authSuccess": "l10n_auth_success.js",
}

HEADER = """/*
  GENERATED by scripts/translate/emit_l10n.py from l10n/*.json -- DO NOT EDIT.
  Edit the English copy in l10n/en.json, re-translate, then re-run the emitter.
  Page: {page}
*/
"""


def load_catalogs(l10n: Path) -> dict:
    """`{locale: {key: value}}` for every catalog in `l10n`, English first."""
    catalogs = {}
    for path in sorted(l10n.glob("*.json")):
        if path.name == "ai-translated-keys.json":
            continue
        locale = path.stem
        data = json.loads(path.read_text(encoding="utf-8"))
        catalogs[locale] = {k: v for k, v in data.items() if not k.startswith("@")}
    if "en" not in catalogs:
        sys.exit(f"No English catalog at {l10n / 'en.json'}")
    return {"en": catalogs.pop("en"), **catalogs}


def js_literal(table: dict) -> str:
    """A JS string literal that JSON.parse()s back to `table`, Jinja-inert."""
    payload = json.dumps(table, ensure_ascii=False, separators=(",", ":"), sort_keys=True)
    return json.dumps(payload, ensure_ascii=False).replace("{", "\\u007b")


def render(page: str, catalogs: dict) -> str:
    prefix = page + "."
    table = {}
    for locale, entries in catalogs.items():
        keys = {k: v for k, v in entries.items() if k.startswith(prefix)}
        # A locale with nothing for this page would only cost bytes and, worse,
        # would resolve as "translated" and suppress the English fallback.
        if keys:
            table[locale] = keys
    return HEADER.format(page=page) + f"window.PANGEA_L10N_STRINGS = JSON.parse({js_literal(table)});\n"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--l10n", default=str(REPO / "l10n"))
    ap.add_argument("--templates", default=str(REPO / "templates"))
    ap.add_argument("--check", action="store_true", help="fail if any generated file is out of date")
    args = ap.parse_args()

    catalogs = load_catalogs(Path(args.l10n))
    templates = Path(args.templates)
    unknown = sorted({k.split(".", 1)[0] for k in catalogs["en"] if "." in k} - set(PAGES))
    if unknown:
        sys.exit(f"l10n/en.json has keys for unknown page(s) {unknown}; add them to PAGES in {Path(__file__).name}")

    stale = []
    for page, filename in sorted(PAGES.items()):
        out = templates / filename
        content = render(page, catalogs)
        if args.check:
            if not out.exists() or out.read_text(encoding="utf-8") != content:
                stale.append(filename)
            continue
        out.write_text(content, encoding="utf-8")
        print(f"wrote templates/{filename} ({len(content)} bytes, {len(catalogs)} locales)")

    if args.check:
        if stale:
            print(
                "::error title=Generated string tables are stale::"
                f"{', '.join(stale)} do not match l10n/. Run "
                "`uv run scripts/translate/emit_l10n.py` and commit the result."
            )
            sys.exit(1)
        print("Generated string tables are up to date.")


if __name__ == "__main__":
    main()
