name: Issue TO TEST enforcement

on:
  issues:
    types: [opened, edited, closed]

jobs:
  process:
    uses: pangeachat/.github/.github/workflows/reusable-issue-to-test-check.yaml@b147c12a80922a768e52953050b9eecf3b924099 # main
    permissions:
      issues: write
