name: Sync issue templates

on:
  schedule:
    - cron: '0 13 * * 1' # weekly Mondays 13:00 UTC
  workflow_dispatch:

jobs:
  sync:
    uses: pangeachat/workflows/.github/workflows/reusable-sync-issue-templates.yaml@89186d0882e8c4923b78175dfd5e295b2b0b9e9a # main
    permissions:
      contents: write
      pull-requests: write
