name: Sync issue templates

on:
  schedule:
    - cron: '0 13 * * 1' # weekly Mondays 13:00 UTC
  workflow_dispatch:

jobs:
  sync:
    uses: pangeachat/workflows/.github/workflows/reusable-sync-issue-templates.yaml@79d6202eee4e21a2dcb816755df101248d83f4c3 # main
    permissions:
      contents: write
      pull-requests: write
